# Generated by Django 3.2.5 on 2021-07-30 15:40

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=40)),
                ('expression', models.TextField(help_text='핵심 표현')),
                ('expression_descript', models.TextField(help_text='핵심 표현 설명')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expression_descript_select', models.CharField(choices=[('ABBREVIATION', '줄임말'), ('NEOLOGISM', '신조어')], default='ABBREVIATION', max_length=20)),
                ('relation_select', models.CharField(choices=[('FAMILY', '가족'), ('FRIEND', '친구')], default='FAMILY', max_length=20)),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
