# Generated by Django 3.2.5 on 2021-08-07 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('expression', models.TextField()),
                ('expression_descript', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('agree', models.BooleanField(default=False)),
                ('expression_descript_select', models.CharField(choices=[('ABBREVIATION', '줄임말'), ('NEOLOGISM', '신조어')], default='ABBREVIATION', max_length=20)),
                ('relation_select', models.CharField(choices=[('FAMILY', '가족'), ('FRIEND', '친구'), ('SENIOR', '선배'), ('WORK', '직장')], default='FAMILY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('en_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentupload')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_content', to='content.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentupload',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='content.TaggedContent', to='content.Tag', verbose_name='Tags'),
        ),
    ]
