# Generated by Django 3.2.5 on 2021-08-10 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentupload',
            name='expression',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='contentupload',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tag',
            name='en_name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='ContentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('like_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_content', to='content.contentupload', verbose_name='좋아요 누른 글')),
                ('like_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_user', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람')),
            ],
            options={
                'unique_together': {('like_user', 'like_content')},
            },
        ),
    ]
