# Generated by Django 3.2.5 on 2021-08-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentupload',
            old_name='author',
            new_name='user',
        ),
    ]
