# Generated by Django 3.2.5 on 2021-08-10 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20210810_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentupload',
            name='likes',
            field=models.ManyToManyField(through='content.ContentLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
