# Generated by Django 3.2.5 on 2021-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210731_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentupload',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
