# Generated by Django 3.2.5 on 2021-08-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_author_contentupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentupload',
            name='user',
        ),
    ]
