# Generated by Django 3.2.5 on 2021-08-11 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20210811_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentupload',
            name='content_like',
        ),
        migrations.RemoveField(
            model_name='contentupload',
            name='content_save',
        ),
        migrations.AddField(
            model_name='contentupload',
            name='likes',
            field=models.ManyToManyField(related_name='saves', through='content.SocialLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentupload',
            name='saves',
            field=models.ManyToManyField(related_name='likes', through='content.SocialSaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
