# Generated by Django 3.2.5 on 2021-08-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_auto_20210811_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.DateTimeField()),
                ('view_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_content', to='content.contentupload', verbose_name='조회한 글')),
                ('view_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_user', to=settings.AUTH_USER_MODEL, verbose_name='조회한 사람')),
            ],
        ),
    ]
