# Generated by Django 3.2.5 on 2021-08-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentupload_writer'),
        ('content', '0003_remove_contentupload_user'),
    ]

    operations = [
    ]
