# Generated by Django 3.2.3 on 2021-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('nickname', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('withdrew_at', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴 시점')),
                ('date_of_birth', models.CharField(blank=True, help_text='생년월일', max_length=32)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('user_age', models.PositiveIntegerField(blank=True, null=True)),
                ('is_login', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
