# Generated by Django 3.2.5 on 2021-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='user_image/user_default.jpg', null=True, upload_to='user_image/'),
        ),
    ]
