# Generated by Django 3.2.5 on 2021-08-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentupload',
            old_name='likes',
            new_name='content_like',
        ),
        migrations.RenameField(
            model_name='contentupload',
            old_name='saves',
            new_name='content_save',
        ),
    ]
